# Generated by Django 5.0.4 on 2024-05-09 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asesores', '0002_alter_asesor_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asesor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='asesor',
            name='usuario',
        ),
        migrations.AddField(
            model_name='asesor',
            name='usuario_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
